- name: copy deployment key to server
  copy: content="{{ deploy_key }}" dest="{{ base_dir }}/.ssh/{{ app_name }}" mode=600
  when: deploy_key is defined

- name: "clone git repository ({{'ssh' if deploy_key is defined else 'https'}}): {{ repo }}"
  git: repo={{ repo }} dest={{ install_dir }} force=yes accept_hostkey=yes key_file="{{ base_dir }}/.ssh/{{ app_name }}" version={{version if version is defined else 'master'}}
  tags: update


- name: npm install locals
  npm:  production=yes path={{install_dir}}
  tags: update


