---
- name: restart nginx
  become: yes
  service: name=nginx state=restarted

- name: reload nginx
  become: yes
  service: name=nginx state=reloaded

- name: reload ufw
  become: yes
  ufw: state=reloaded
